name: Start tests and deploy
on:
  push:
jobs:
  load:
    runs-on: windows-latest
    steps:                
    - name: Checkout       
      uses: actions/checkout@v4.1.6
    - name: Dependencies
      run: pip install -r src/requirements.txt 
    - name: GetModel 
      run: python ./src/getmodel.py
  lauch:
    runs-on: windows-latest
    needs: load
    steps:    
    - name: Checkout       
      uses: actions/checkout@v4.1.6
    - name: CheckDependencies
      run:  pip list 
    - name: LoadFlask
      run:  pip install Flask Flask-Uploads Flask-WTF
    - name: ActivateFlas
      run:  python src/app.py
    - name: RunFlask 
      run:  flask --app src/app.py run --host=0.0.0.0 --port=4000